version: '3.4'

services:
  nginx1:
    image: "nginx:latest"
    container_name: nginx1
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
  nginx2:
    image: "nginx:latest"
    container_name: nginx2
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro

  traefik:
    image: "traefik:latest"
    container_name: traefik
    volumes:
      - ./traefik.yaml:/traefik.yaml:ro
    ports:
      - 80:80
    depends_on:
      - nginx1
      - nginx2
