version: '3.4'
services:
  nginx1:
    image: "nginx:latest"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro

  nginx2:
    image: "nginx:latest"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro

  traefik:
    image: "traefik:latest"
    volumes:
      - ./traefik.yaml:/traefik.yaml:ro
    ports:
      - 80:80
    depends_on:
      - nginx1
      - nginx2
