version: '3.4'
services:
  nginx1:
    image: "nginx:latest"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    cap_add:
      - CHOWN
      - NET_BIND_SERVICE
      - SETGID
      - SETUID
    cap_drop:
      - ALL

  nginx2:
    image: "nginx:latest"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    cap_add:
      - CHOWN
      - NET_BIND_SERVICE
      - SETGID
      - SETUID
    cap_drop:
      - ALL

  traefik:
    image: "traefik:latest"
    volumes:
      - ./traefik.yaml:/traefik.yaml:ro
    cap_drop:
      - ALL
    ports:
      - 80:80
    depends_on:
      - nginx1
      - nginx2
